name: Push

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions: read-all

jobs:
  release:
    permissions:
      contents: write
    uses: quike/workflow-github/.github/workflows/release.yml@15a6f8baec0dea98eb96de5766c595404ae3424d # v1
    secrets: inherit

  build:
    needs: release
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version-file: go.mod
      - name: Release outputs
        run: |
          echo "release-published: ${{ needs.release.outputs.release-published }}"
          echo "release-version:   ${{ needs.release.outputs.release-version }}"
          echo "release-major:     ${{ needs.release.outputs.release-major }}"
          echo "release-minor:     ${{ needs.release.outputs.release-minor }}"
          echo "release-patch:     ${{ needs.release.outputs.release-patch }}"
          echo "release-type:      ${{ needs.release.outputs.release-type }}"
          echo "release-git-head:  ${{ needs.release.outputs.release-git-head }}"
          echo "release-git-tag:   ${{ needs.release.outputs.release-git-tag }}"
      - name: Build
        env:
          RELEASE_VERSION: ${{ needs.release.outputs.release-version }}
        run: make build VERSION="${RELEASE_VERSION:-0.0.0}"
      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7
        with:
          files: target/coverage.out
          token: ${{ secrets.CODECOV_TOKEN }}
