name: Push

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions: read-all

jobs:
  release:
    permissions:
      contents: write
    uses: quike/workflow-github/.github/workflows/release.yml@2840fd5aff5f259fa27b1c59fefb8c857a366c34 # v1
    secrets: inherit

  build:
    needs: release
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version-file: go.mod
      - name: Release outputs
        run: |
          echo "release-published: ${{ needs.release.outputs.release-published }}"
          echo "release-version:   ${{ needs.release.outputs.release-version }}"
          echo "release-major:     ${{ needs.release.outputs.release-major }}"
          echo "release-minor:     ${{ needs.release.outputs.release-minor }}"
          echo "release-patch:     ${{ needs.release.outputs.release-patch }}"
          echo "release-type:      ${{ needs.release.outputs.release-type }}"
          echo "release-git-head:  ${{ needs.release.outputs.release-git-head }}"
          echo "release-git-tag:   ${{ needs.release.outputs.release-git-tag }}"
      - name: Build
        env:
          RELEASE_VERSION: ${{ needs.release.outputs.release-version }}
        run: make build VERSION="${RELEASE_VERSION:-0.0.0}"
      - uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6
        with:
          files: target/coverage.out
          token: ${{ secrets.CODECOV_TOKEN }}
